# The robot description defines the generalized coordinates and how to map those
# to the underlying URDF dofs.

api_version: 1.0

# Defines the generalized coordinates. Each generalized coordinate is assumed
# to have an entry in the URDF.
# Lula will only use these joints to control the robot position.
cspace:
    - torso_lift_joint
    - head_pan_joint
    - laser_tilt_mount_joint
    - r_shoulder_pan_joint
    - l_shoulder_pan_joint
    - head_tilt_joint
    - r_shoulder_lift_joint
    - l_shoulder_lift_joint
    - r_upper_arm_roll_joint
    - l_upper_arm_roll_joint
    - r_elbow_flex_joint
    - l_elbow_flex_joint
    - r_forearm_roll_joint
    - l_forearm_roll_joint
    - r_wrist_flex_joint
    - l_wrist_flex_joint
    #- r_wrist_roll_joint
    #- l_wrist_roll_joint
default_q: [
    0.0,0.0026,-0.7854,0.0595,0.0613,-0.4712,1.3963,1.3963,-0.9602,-0.6813,-0.0,-0.0,5.3526,4.6041,-0.0165,-0.1267
]

# Most dimensions of the cspace have a direct corresponding element
# in the URDF. This list of rules defines how unspecified coordinates
# should be extracted or how values in the URDF should be overwritten.

cspace_to_urdf_rules:
    - {name: fl_caster_rotation_joint, rule: fixed, value: 0.0}
    - {name: fr_caster_rotation_joint, rule: fixed, value: 0.0}
    - {name: bl_caster_rotation_joint, rule: fixed, value: 0.0}
    - {name: br_caster_rotation_joint, rule: fixed, value: 0.0}
    - {name: fl_caster_l_wheel_joint, rule: fixed, value: -0.0}
    - {name: fl_caster_r_wheel_joint, rule: fixed, value: -0.0}
    - {name: fr_caster_l_wheel_joint, rule: fixed, value: -0.0}
    - {name: fr_caster_r_wheel_joint, rule: fixed, value: -0.0}
    - {name: bl_caster_l_wheel_joint, rule: fixed, value: -0.0}
    - {name: bl_caster_r_wheel_joint, rule: fixed, value: -0.0}
    - {name: br_caster_l_wheel_joint, rule: fixed, value: -0.0}
    - {name: br_caster_r_wheel_joint, rule: fixed, value: -0.0}
    - {name: r_gripper_l_finger_joint, rule: fixed, value: -0.0}
    - {name: r_gripper_r_finger_joint, rule: fixed, value: -0.0}
    - {name: l_gripper_l_finger_joint, rule: fixed, value: -0.0}
    - {name: l_gripper_r_finger_joint, rule: fixed, value: -0.0}
    - {name: r_gripper_l_finger_tip_joint, rule: fixed, value: -0.548}
    - {name: r_gripper_r_finger_tip_joint, rule: fixed, value: -0.548}
    - {name: l_gripper_l_finger_tip_joint, rule: fixed, value: -0.548}
    - {name: l_gripper_r_finger_tip_joint, rule: fixed, value: -0.548}

# Lula uses collision spheres to define the robot geometry in order to avoid
# collisions with external obstacles.  If no spheres are specified, Lula will
# not be able to avoid obstacles.

collision_spheres:
  - base_link:
    - "center": [-0.215, 0.005, 0.116]
      "radius": 0.215
    - "center": [0.041, 0.215, 0.115]
      "radius": 0.215
    - "center": [0.095, 0.016, 0.115]
      "radius": 0.215
    - "center": [-0.204, -0.229, 0.115]
      "radius": 0.215
    - "center": [0.217, 0.014, 0.115]
      "radius": 0.215
    - "center": [-0.177, 0.213, 0.115]
      "radius": 0.215
    - "center": [0.219, -0.207, 0.115]
      "radius": 0.215
    - "center": [-0.017, -0.21, 0.115]
      "radius": 0.215
    - "center": [0.211, 0.214, 0.115]
      "radius": 0.215
  - r_forearm_roll_link:
    - "center": [0.11, -0.0, -0.0]
      "radius": 0.077
  - r_forearm_link:
    - "center": [0.139, 0.001, -0.001]
      "radius": 0.08
    - "center": [0.21, 0.005, -0.011]
      "radius": 0.072
    - "center": [0.255, -0.029, -0.019]
      "radius": 0.063
    - "center": [0.245, 0.031, -0.018]
      "radius": 0.063
    - "center": [0.139, 0.001, -0.001]
      "radius": 0.095
    - "center": [0.235, 0.004, -0.015]
      "radius": 0.087
    - "center": [0.306, -0.001, -0.002]
      "radius": 0.078
  - l_shoulder_pan_link:
    - "center": [-0.031, 0.003, -0.008]
      "radius": 0.194
    - "center": [-0.035, 0.006, -0.402]
      "radius": 0.189
    - "center": [-0.048, 0.005, -0.253]
      "radius": 0.179
    - "center": [0.073, 0.016, 0.034]
      "radius": 0.192
    - "center": [-0.042, -0.032, -0.127]
      "radius": 0.174
  - l_shoulder_lift_link:
    - "center": [0.034, 0.021, -0.031]
      "radius": 0.201
  - r_shoulder_lift_link:
    - "center": [0.034, 0.021, -0.027]
      "radius": 0.201
  - r_shoulder_pan_link:
    - "center": [0.083, 0.003, -0.016]
      "radius": 0.194
    - "center": [-0.035, 0.006, -0.402]
      "radius": 0.189
    - "center": [-0.048, 0.005, -0.253]
      "radius": 0.179
    - "center": [-0.01, 0.016, 0.034]
      "radius": 0.192
    - "center": [-0.042, -0.032, -0.127]
      "radius": 0.174
  - r_upper_arm_link:
    - "center": [0.207, -0.0, -0.011]
      "radius": 0.137
    - "center": [0.27, 0.003, -0.034]
      "radius": 0.12
    - "center": [0.19, -0.001, 0.007]
      "radius": 0.134
    - "center": [0.407, -0.044, -0.005]
      "radius": 0.094
    - "center": [0.401, 0.044, -0.012]
      "radius": 0.094
  - l_upper_arm_link:
    - "center": [0.207, -0.0, -0.011]
      "radius": 0.137
    - "center": [0.27, 0.003, -0.034]
      "radius": 0.12
    - "center": [0.19, -0.001, 0.007]
      "radius": 0.134
    - "center": [0.407, -0.044, -0.005]
      "radius": 0.094
    - "center": [0.401, 0.044, -0.012]
      "radius": 0.094
  - l_forearm_link:
    - "center": [0.139, 0.001, -0.001]
      "radius": 0.095
    - "center": [0.21, 0.005, -0.011]
      "radius": 0.087
    - "center": [0.311, -0.002, -0.013]
      "radius": 0.078
